local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.git_files, {})
vim.keymap.set('n', '<leader>fa', builtin.find_files, {})
vim.keymap.set('n', '<leader>ft', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', function() builtin.buffers({sort_lastused = true}) end, {})
vim.keymap.set('n', '<leader>fy', builtin.lsp_document_symbols, {})
